# Generated by Django 4.1.7 on 2023-03-26 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='blood_type',
            field=models.CharField(choices=[('AP', 'A+'), ('AN', 'A-'), ('BP', 'B+'), ('BN', 'B-'), ('ABP', 'AB+'), ('ABN', 'AB-'), ('OP', 'O+'), ('ON', 'O-')], max_length=3),
        ),
    ]
