# Generated by Django 4.1.7 on 2023-03-26 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Donors', '0002_alter_donor_blood_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('donor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Donors.donor')),
                ('phone', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=255)),
            ],
        ),
    ]
