# Generated by Django 4.1.7 on 2023-03-26 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Donors', '0003_contactinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postal_code', models.CharField(max_length=7)),
                ('civic_number', models.PositiveSmallIntegerField()),
                ('street', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('province', models.CharField(choices=[('AB', 'Alberta'), ('BC', 'British Columbia'), ('MB', 'Manitoba'), ('NB', 'New Brunswick'), ('NL', 'Newfoundland and Labrador'), ('NT', 'Norhtwest Territories'), ('NS', 'Nova Scotia'), ('NU', 'Nunavut'), ('ON', 'Ontario'), ('PE', 'Prince Edward Island'), ('QC', 'Quebec'), ('SK', 'Saskatchewan'), ('YT', 'Yukon')], max_length=2)),
            ],
        ),
        migrations.AddConstraint(
            model_name='donor',
            constraint=models.CheckConstraint(check=models.Q(('blood_type__in', ('AP', 'AN', 'BP', 'BN', 'ABP', 'ABN', 'OP', 'ON'))), name='blood_type'),
        ),
        migrations.AddField(
            model_name='shippinginfo',
            name='donor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Donors.donor'),
        ),
        migrations.AddConstraint(
            model_name='shippinginfo',
            constraint=models.CheckConstraint(check=models.Q(('province__in', ('AB', 'BC', 'MB', 'NB', 'NL', 'NT', 'NS', 'NU', 'ON', 'PE', 'QC', 'SK', 'YT'))), name='province_invalid'),
        ),
        migrations.AddConstraint(
            model_name='shippinginfo',
            constraint=models.CheckConstraint(check=models.Q(('civic_number__gt', 0)), name='civic_number_invalid'),
        ),
    ]
