# Generated by Django 4.1.7 on 2023-03-26 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Warehouses', '0001_initial'),
        ('Donors', '0006_alter_shippinginfo_donor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('donation_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_collected', models.DateField(auto_now_add=True)),
                ('rejected', models.BooleanField(default=False)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Donors.donor')),
                ('located', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='Warehouses.warehouse')),
            ],
        ),
    ]
