# Generated by Django 4.1.7 on 2023-03-28 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Donors', '0002_initial'),
        ('Warehouses', '0002_initial'),
        ('Donations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_collected', models.DateField(auto_now_add=True)),
                ('rejected', models.BooleanField(default=False)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Donors.donor')),
                ('located', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Warehouses.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='PlasmaDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PlateletDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PlateletDonationDonations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Donations.donation')),
                ('platelet_donation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Donations.plateletdonation')),
            ],
        ),
        migrations.AddField(
            model_name='plateletdonation',
            name='donations',
            field=models.ManyToManyField(through='Donations.PlateletDonationDonations', to='Donations.donation'),
        ),
        migrations.CreateModel(
            name='PlasmaDonationDonations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Donations.donation')),
                ('plasma_donation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Donations.plasmadonation')),
            ],
        ),
        migrations.AddField(
            model_name='plasmadonation',
            name='donations',
            field=models.ManyToManyField(through='Donations.PlasmaDonationDonations', to='Donations.donation'),
        ),
        migrations.CreateModel(
            name='BloodDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='Donations.donation')),
                ('located', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Warehouses.warehouse')),
            ],
        ),
    ]
