# Generated by Django 4.1.7 on 2023-03-28 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Warehouses', '0002_initial'),
        ('Donations', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='donation_used',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infection', models.CharField(blank=True, choices=[('Syphilis', 'Syphilis'), ('HEP_B', 'Hepatitis B'), ('HEP_C', 'Hepatitis C'), ('HIV_1', 'Human Immunodeficiency Virus 1'), ('HIV_2', 'Human Immunodeficiency Virus 2'), ('HTLV_1', 'Human T-Lymphotropic Virus 1'), ('HTLV_2', 'Human T-Lymphotropic Virus 2'), ('WNV', 'West Nile Virus'), ('CMV', 'Cytomegalovirus'), ('CD', 'Chagas Disease  ')], default=None, max_length=127, null=True)),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Donations.donation')),
                ('located', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Warehouses.warehouse')),
            ],
        ),
    ]
