# Generated by Django 4.1.7 on 2023-03-30 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Warehouses', '0002_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShippingInfo',
            new_name='WarehouseShippingInfo',
        ),
    ]
